
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AS_NUMBER IP PIPE PREFIX STATE TABLE_DUMP2 TIMESTAMPlinea : TABLE_DUMP2 PIPE TIMESTAMP PIPE STATE PIPE IP PIPE AS_NUMBER PIPE PREFIX PIPE as_pathas_path : as_path AS_NUMBER\n               | as_path TIMESTAMP\n               | AS_NUMBER\n               | TIMESTAMP'
    
_lr_action_items = {'TABLE_DUMP2':([0,],[2,]),'$end':([1,14,15,16,17,18,],[0,-5,-4,-1,-3,-2,]),'PIPE':([2,4,6,8,10,12,],[3,5,7,9,11,13,]),'TIMESTAMP':([3,13,14,15,16,17,18,],[4,14,-5,-4,17,-3,-2,]),'STATE':([5,],[6,]),'IP':([7,],[8,]),'AS_NUMBER':([9,13,14,15,16,17,18,],[10,15,-5,-4,18,-3,-2,]),'PREFIX':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'linea':([0,],[1,]),'as_path':([13,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> linea","S'",1,None,None,None),
  ('linea -> TABLE_DUMP2 PIPE TIMESTAMP PIPE STATE PIPE IP PIPE AS_NUMBER PIPE PREFIX PIPE as_path','linea',13,'p_ruta_bgp','parser.py',114),
  ('as_path -> as_path AS_NUMBER','as_path',2,'p_as_path','parser.py',122),
  ('as_path -> as_path TIMESTAMP','as_path',2,'p_as_path','parser.py',123),
  ('as_path -> AS_NUMBER','as_path',1,'p_as_path','parser.py',124),
  ('as_path -> TIMESTAMP','as_path',1,'p_as_path','parser.py',125),
]
